pyproject.toml: six is a required dependency
When not installed, a clean/fresh install results in:

	$ bmaptool --version
	Traceback (most recent call last):
	  File "/2opt/devel/bmaptool/venv.python3.11/bin/bmaptool", line 5, in <module>
	    from bmaptool.CLI import main
	  File "/2opt/devel/bmaptool/venv.python3.11/lib64/python3.11/site-packages/bmaptool/CLI.py", line 42, in <module>
	    from . import BmapCreate, BmapCopy, BmapHelpers, TransRead
	  File "/2opt/devel/bmaptool/venv.python3.11/lib64/python3.11/site-packages/bmaptool/TransRead.py", line 36, in <module>
	    from six.moves.urllib import parse as urlparse
	ModuleNotFoundError: No module named 'six'

Signed-off-by: Trevor Woerner <twoerner@gmail.com>